MODE_TEST = "test"

SIGNAL_SIDE_POSITIVE = "positive"
SIGNAL_SIDE_NEGATIVE = "negative"

ORDER_DIRECTION_LONG = "Long"
ORDER_DIRECTION_SHORT = "Short"

ORDER_DIRECTION_BUY = "Buy"
ORDER_DIRECTION_SELL = "Sell"

ORDER_TYPE_LIMIT = "Limit"
ORDER_TYPE_MARKET = "Market"

ORDER_TIF_GOOD_TILL_CANCEL = "GoodTillCancel"
ORDER_TIF_POST_ONLY = "PostOnly"

ACTIVE_ORDER_STATUS = "Created,New,PartiallyFilled,Active"
ORDER_STATUS_ACTIVE = "Order Active"
ORDER_STATUS_PARTIAL_FILL = "Partial Fill"
# ORDER_STATUS_TRADE_COMPLETE = "Trade Complete"
ORDER_STATUS_POSITION_FILLED = "Position Filled"
ORDER_STATUS_TRY_AGAIN = "Try Again"

# Kill Switch
KILL_SWITCH_CAN_DO_NEW_TRADE = 0
KILL_SWITCH_OPENED_POSITION = 1
KILL_SWITCH_CLOSE_ORDER_POSITION = 2
